apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: "{{ .Values.adservice.image }}:{{ .Values.adservice.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.adservice.port }}
          env:
            - name: PORT
              value: "{{ .Values.adservice.port }}"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.adservice.port }}"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.adservice.port }}"]
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - name: grpc
      port: {{ .Values.adservice.port }}
      targetPort: {{ .Values.adservice.port }}
