apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
    app.kubernetes.io/name: online-boutique
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: server
          image: "{{ .Values.currencyservice.image }}:{{ .Values.currencyservice.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.currencyservice.port }}
          env:
            - name: PORT
              value: "{{ .Values.currencyservice.port }}"
          readinessProbe:
            tcpSocket:
              port: {{ .Values.currencyservice.port }}
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.currencyservice.port }}
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
    - name: grpc
      port: {{ .Values.currencyservice.port }}
      targetPort: {{ .Values.currencyservice.port }}
